/* eslint-disable no-unused-vars */
import pr1 from '../assets/images/products/f1.jpg'
import pr2 from '../assets/images/products/f2.jpg'
import pr3 from '../assets/images/products/f3.jpg'
import pr4 from '../assets/images/products/f4.jpg'
import pr5 from '../assets/images/products/f5.jpg'
import pr6 from '../assets/images/products/f6.jpg'
import pr7 from '../assets/images/products/f7.jpg'
import pr8 from '../assets/images/products/f8.jpg'
import pro1 from '../assets/images/products/n1.jpg'
import pro2 from '../assets/images/products/n2.jpg'
import pro3 from '../assets/images/products/n3.jpg'
import pro4 from '../assets/images/products/n4.jpg'
import pro5 from '../assets/images/products/n5.jpg'
import pro6 from '../assets/images/products/n6.jpg'
import pro7 from '../assets/images/products/n7.jpg'
import pro8 from '../assets/images/products/n8.jpg'
import img1 from '../assets/images/products/img1.png'
import img2 from '../assets/images/products/img2.png'
import img3 from '../assets/images/products/img3.png'
import img4 from '../assets/images/products/img4.png'
import img5 from '../assets/images/products/img5.png'
import img6 from '../assets/images/products/img6.png'
import img7 from '../assets/images/products/img7.png'
import img8 from '../assets/images/products/img8.png'

// eslint-disable-next-line react-refresh/only-export-components
export const PRODUCTS = [
    {
        "id": 1,
        "productName": "Broom - Corn",
        "price": 10,
        "views": 66,
        "likes": 75,
        "dislikes": 53,
        "addToCart": 9,
        "purchases": 64,
        "normalRating": 1.08
    },
    {
        "id": 2,
        "productName": "Peppercorns - Green",
        "price": 78,
        "views": 96,
        "likes": 78,
        "dislikes": 45,
        "addToCart": 27,
        "purchases": 82,
        "normalRating": 4.12
    },
    {
        "id": 3,
        "productName": "Tea - Orange Pekoe",
        "price": 89,
        "views": 28,
        "likes": 19,
        "dislikes": 29,
        "addToCart": 85,
        "purchases": 59,
        "normalRating": 4.44
    },
    {
        "id": 4,
        "productName": "Wine - Ruffino Chianti Classico",
        "price": 44,
        "views": 52,
        "likes": 93,
        "dislikes": 24,
        "addToCart": 48,
        "purchases": 21,
        "normalRating": 5.0
    },
    {
        "id": 5,
        "productName": "Longos - Penne With Pesto",
        "price": 66,
        "views": 16,
        "likes": 93,
        "dislikes": 85,
        "addToCart": 28,
        "purchases": 61,
        "normalRating": 3.64
    },
    {
        "id": 6,
        "productName": "Towel Dispenser",
        "price": 76,
        "views": 74,
        "likes": 8,
        "dislikes": 69,
        "addToCart": 65,
        "purchases": 32,
        "normalRating": 1.35
    },
    {
        "id": 7,
        "productName": "Sproutsmustard Cress",
        "price": 14,
        "views": 46,
        "likes": 3,
        "dislikes": 79,
        "addToCart": 74,
        "purchases": 73,
        "normalRating": 4.95
    },
    {
        "id": 8,
        "productName": "Beef Flat Iron Steak",
        "price": 100,
        "views": 43,
        "likes": 95,
        "dislikes": 48,
        "addToCart": 87,
        "purchases": 25,
        "normalRating": 4.43
    },
    {
        "id": 9,
        "productName": "Banana Turning",
        "price": 88,
        "views": 77,
        "likes": 48,
        "dislikes": 57,
        "addToCart": 30,
        "purchases": 33,
        "normalRating": 3.38
    },
    {
        "id": 10,
        "productName": "Icecream - Dstk Cml And Fdg",
        "price": 72,
        "views": 32,
        "likes": 74,
        "dislikes": 19,
        "addToCart": 79,
        "purchases": 10,
        "normalRating": 1.31
    },
    {
        "id": 11,
        "productName": "Scotch - Queen Anne",
        "price": 54,
        "views": 53,
        "likes": 64,
        "dislikes": 59,
        "addToCart": 99,
        "purchases": 80,
        "normalRating": 1.89
    },
    {
        "id": 12,
        "productName": "Cup - 3.5oz, Foam",
        "price": 54,
        "views": 79,
        "likes": 51,
        "dislikes": 58,
        "addToCart": 89,
        "purchases": 8,
        "normalRating": 4.7
    },
    {
        "id": 13,
        "productName": "French Pastry - Mini Chocolate",
        "price": 40,
        "views": 60,
        "likes": 9,
        "dislikes": 45,
        "addToCart": 27,
        "purchases": 37,
        "normalRating": 3.77
    },
    {
        "id": 14,
        "productName": "Yokaline",
        "price": 86,
        "views": 4,
        "likes": 88,
        "dislikes": 49,
        "addToCart": 93,
        "purchases": 84,
        "normalRating": 1.11
    },
    {
        "id": 15,
        "productName": "Soup - Campbells Beef Stew",
        "price": 68,
        "views": 46,
        "likes": 89,
        "dislikes": 39,
        "addToCart": 30,
        "purchases": 10,
        "normalRating": 3.73
    },
    {
        "id": 16,
        "productName": "Cherries - Frozen",
        "price": 72,
        "views": 90,
        "likes": 95,
        "dislikes": 87,
        "addToCart": 89,
        "purchases": 26,
        "normalRating": 1.79
    },
    {
        "id": 17,
        "productName": "Crush - Orange, 355ml",
        "price": 1,
        "views": 41,
        "likes": 62,
        "dislikes": 67,
        "addToCart": 22,
        "purchases": 92,
        "normalRating": 3.73
    },
    {
        "id": 18,
        "productName": "Apple - Custard",
        "price": 57,
        "views": 15,
        "likes": 54,
        "dislikes": 33,
        "addToCart": 53,
        "purchases": 42,
        "normalRating": 1.66
    },
    {
        "id": 19,
        "productName": "Wine - Winzer Krems Gruner",
        "price": 33,
        "views": 71,
        "likes": 96,
        "dislikes": 13,
        "addToCart": 38,
        "purchases": 20,
        "normalRating": 4.43
    },
    {
        "id": 20,
        "productName": "Hot Chocolate - Individual",
        "price": 41,
        "views": 4,
        "likes": 11,
        "dislikes": 10,
        "addToCart": 60,
        "purchases": 59,
        "normalRating": 1.52
    },
    {
        "id": 21,
        "productName": "Wine - Chateauneuf Du Pape",
        "price": 50,
        "views": 34,
        "likes": 41,
        "dislikes": 5,
        "addToCart": 78,
        "purchases": 24,
        "normalRating": 3.94
    },
    {
        "id": 22,
        "productName": "Scallops - 10/20",
        "price": 35,
        "views": 36,
        "likes": 83,
        "dislikes": 29,
        "addToCart": 46,
        "purchases": 34,
        "normalRating": 1.67
    },
    {
        "id": 23,
        "productName": "Longos - Lasagna Beef",
        "price": 61,
        "views": 98,
        "likes": 41,
        "dislikes": 25,
        "addToCart": 34,
        "purchases": 82,
        "normalRating": 2.79
    },
    {
        "id": 24,
        "productName": "Pancetta",
        "price": 47,
        "views": 63,
        "likes": 19,
        "dislikes": 29,
        "addToCart": 89,
        "purchases": 31,
        "normalRating": 2.13
    },
    {
        "id": 25,
        "productName": "Tart - Lemon",
        "price": 45,
        "views": 9,
        "likes": 94,
        "dislikes": 77,
        "addToCart": 69,
        "purchases": 8,
        "normalRating": 3.98
    },
    {
        "id": 26,
        "productName": "Plate Foam Laminated 9in Blk",
        "price": 18,
        "views": 91,
        "likes": 7,
        "dislikes": 97,
        "addToCart": 44,
        "purchases": 37,
        "normalRating": 1.79
    },
    {
        "id": 27,
        "productName": "Eggs - Extra Large",
        "price": 94,
        "views": 56,
        "likes": 91,
        "dislikes": 44,
        "addToCart": 60,
        "purchases": 20,
        "normalRating": 2.07
    },
    {
        "id": 28,
        "productName": "Lotus Leaves",
        "price": 94,
        "views": 94,
        "likes": 48,
        "dislikes": 53,
        "addToCart": 83,
        "purchases": 15,
        "normalRating": 4.58
    },
    {
        "id": 29,
        "productName": "Milk - 1%",
        "price": 2,
        "views": 7,
        "likes": 63,
        "dislikes": 22,
        "addToCart": 50,
        "purchases": 29,
        "normalRating": 3.37
    },
    {
        "id": 30,
        "productName": "Tuna - Canned, Flaked, Light",
        "price": 90,
        "views": 98,
        "likes": 8,
        "dislikes": 10,
        "addToCart": 78,
        "purchases": 37,
        "normalRating": 1.68
    },
    {
        "id": 31,
        "productName": "Bread Bowl Plain",
        "price": 20,
        "views": 52,
        "likes": 31,
        "dislikes": 34,
        "addToCart": 31,
        "purchases": 3,
        "normalRating": 1.7
    },
    {
        "id": 32,
        "productName": "Juice - Lagoon Mango",
        "price": 60,
        "views": 3,
        "likes": 64,
        "dislikes": 38,
        "addToCart": 36,
        "purchases": 80,
        "normalRating": 3.96
    },
    {
        "id": 33,
        "productName": "Pastrami",
        "price": 77,
        "views": 71,
        "likes": 84,
        "dislikes": 98,
        "addToCart": 5,
        "purchases": 23,
        "normalRating": 1.23
    },
    {
        "id": 34,
        "productName": "Cotton Wet Mop 16 Oz",
        "price": 98,
        "views": 78,
        "likes": 37,
        "dislikes": 63,
        "addToCart": 23,
        "purchases": 5,
        "normalRating": 2.57
    },
    {
        "id": 35,
        "productName": "Venison - Ground",
        "price": 12,
        "views": 55,
        "likes": 34,
        "dislikes": 18,
        "addToCart": 51,
        "purchases": 34,
        "normalRating": 4.87
    },
    {
        "id": 36,
        "productName": "Tomato - Peeled Italian Canned",
        "price": 29,
        "views": 24,
        "likes": 30,
        "dislikes": 36,
        "addToCart": 61,
        "purchases": 14,
        "normalRating": 2.59
    },
    {
        "id": 37,
        "productName": "Cup Translucent 9 Oz",
        "price": 74,
        "views": 28,
        "likes": 42,
        "dislikes": 11,
        "addToCart": 30,
        "purchases": 17,
        "normalRating": 2.86
    },
    {
        "id": 38,
        "productName": "Roe - Flying Fish",
        "price": 55,
        "views": 82,
        "likes": 11,
        "dislikes": 28,
        "addToCart": 59,
        "purchases": 58,
        "normalRating": 4.19
    },
    {
        "id": 39,
        "productName": "Soup - Campbells, Chix Gumbo",
        "price": 3,
        "views": 80,
        "likes": 75,
        "dislikes": 61,
        "addToCart": 40,
        "purchases": 96,
        "normalRating": 2.64
    },
    {
        "id": 40,
        "productName": "Tea - Earl Grey",
        "price": 88,
        "views": 19,
        "likes": 13,
        "dislikes": 29,
        "addToCart": 9,
        "purchases": 24,
        "normalRating": 3.94
    },
    {
        "id": 41,
        "productName": "Extract - Lemon",
        "price": 56,
        "views": 18,
        "likes": 99,
        "dislikes": 1,
        "addToCart": 20,
        "purchases": 90,
        "normalRating": 2.03
    },
    {
        "id": 42,
        "productName": "Pasta - Fusili Tri - Coloured",
        "price": 78,
        "views": 50,
        "likes": 40,
        "dislikes": 68,
        "addToCart": 70,
        "purchases": 28,
        "normalRating": 4.31
    },
    {
        "id": 43,
        "productName": "Ham - Smoked, Bone - In",
        "price": 7,
        "views": 39,
        "likes": 94,
        "dislikes": 95,
        "addToCart": 95,
        "purchases": 38,
        "normalRating": 1.24
    },
    {
        "id": 44,
        "productName": "Pomello",
        "price": 51,
        "views": 100,
        "likes": 10,
        "dislikes": 65,
        "addToCart": 96,
        "purchases": 15,
        "normalRating": 3.7
    },
    {
        "id": 45,
        "productName": "Ecolab Crystal Fusion",
        "price": 78,
        "views": 66,
        "likes": 30,
        "dislikes": 41,
        "addToCart": 15,
        "purchases": 58,
        "normalRating": 1.94
    },
    {
        "id": 46,
        "productName": "Chocolate - Feathers",
        "price": 24,
        "views": 33,
        "likes": 68,
        "dislikes": 54,
        "addToCart": 22,
        "purchases": 77,
        "normalRating": 1.38
    },
    {
        "id": 47,
        "productName": "Yogurt - Cherry, 175 Gr",
        "price": 18,
        "views": 62,
        "likes": 86,
        "dislikes": 28,
        "addToCart": 74,
        "purchases": 81,
        "normalRating": 3.91
    },
    {
        "id": 48,
        "productName": "Turkey - Oven Roast Breast",
        "price": 55,
        "views": 39,
        "likes": 71,
        "dislikes": 1,
        "addToCart": 8,
        "purchases": 40,
        "normalRating": 2.2
    },
    {
        "id": 49,
        "productName": "Wine - Delicato Merlot",
        "price": 8,
        "views": 86,
        "likes": 66,
        "dislikes": 36,
        "addToCart": 70,
        "purchases": 62,
        "normalRating": 1.3
    },
    {
        "id": 50,
        "productName": "Pepper - Sorrano",
        "price": 33,
        "views": 25,
        "likes": 1,
        "dislikes": 84,
        "addToCart": 81,
        "purchases": 6,
        "normalRating": 2.57
    },
    {
        "id": 51,
        "productName": "Cheese - Grie Des Champ",
        "price": 62,
        "views": 7,
        "likes": 77,
        "dislikes": 12,
        "addToCart": 90,
        "purchases": 86,
        "normalRating": 3.47
    },
    {
        "id": 52,
        "productName": "Ice Cream - Vanilla",
        "price": 40,
        "views": 47,
        "likes": 80,
        "dislikes": 47,
        "addToCart": 88,
        "purchases": 88,
        "normalRating": 3.58
    },
    {
        "id": 53,
        "productName": "Juice Peach Nectar",
        "price": 4,
        "views": 83,
        "likes": 32,
        "dislikes": 69,
        "addToCart": 29,
        "purchases": 12,
        "normalRating": 1.06
    },
    {
        "id": 54,
        "productName": "Cod - Black Whole Fillet",
        "price": 65,
        "views": 37,
        "likes": 33,
        "dislikes": 95,
        "addToCart": 53,
        "purchases": 19,
        "normalRating": 1.6
    },
    {
        "id": 55,
        "productName": "Soup - Campbells - Chicken Noodle",
        "price": 72,
        "views": 64,
        "likes": 54,
        "dislikes": 5,
        "addToCart": 34,
        "purchases": 30,
        "normalRating": 2.21
    },
    {
        "id": 56,
        "productName": "Kellogs Special K Cereal",
        "price": 24,
        "views": 79,
        "likes": 77,
        "dislikes": 37,
        "addToCart": 51,
        "purchases": 63,
        "normalRating": 1.66
    },
    {
        "id": 57,
        "productName": "Crab - Soft Shell",
        "price": 2,
        "views": 97,
        "likes": 59,
        "dislikes": 60,
        "addToCart": 56,
        "purchases": 21,
        "normalRating": 4.62
    },
    {
        "id": 58,
        "productName": "Coffee - Almond Amaretto",
        "price": 92,
        "views": 73,
        "likes": 96,
        "dislikes": 97,
        "addToCart": 56,
        "purchases": 45,
        "normalRating": 3.78
    },
    {
        "id": 59,
        "productName": "Ice Cream - Fudge Bars",
        "price": 99,
        "views": 24,
        "likes": 68,
        "dislikes": 11,
        "addToCart": 76,
        "purchases": 91,
        "normalRating": 3.98
    },
    {
        "id": 60,
        "productName": "Island Oasis - Ice Cream Mix",
        "price": 14,
        "views": 34,
        "likes": 23,
        "dislikes": 28,
        "addToCart": 76,
        "purchases": 50,
        "normalRating": 4.6
    },
    {
        "id": 61,
        "productName": "Bag - Regular Kraft 20 Lb",
        "price": 98,
        "views": 20,
        "likes": 90,
        "dislikes": 31,
        "addToCart": 100,
        "purchases": 25,
        "normalRating": 3.06
    },
    {
        "id": 62,
        "productName": "Tumeric",
        "price": 30,
        "views": 65,
        "likes": 76,
        "dislikes": 82,
        "addToCart": 51,
        "purchases": 51,
        "normalRating": 3.82
    },
    {
        "id": 63,
        "productName": "Wine - Chardonnay South",
        "price": 14,
        "views": 21,
        "likes": 93,
        "dislikes": 75,
        "addToCart": 70,
        "purchases": 14,
        "normalRating": 3.77
    },
    {
        "id": 64,
        "productName": "Juice - Propel Sport",
        "price": 46,
        "views": 59,
        "likes": 68,
        "dislikes": 57,
        "addToCart": 26,
        "purchases": 46,
        "normalRating": 1.38
    },
    {
        "id": 65,
        "productName": "Appetizer - Mushroom Tart",
        "price": 48,
        "views": 98,
        "likes": 30,
        "dislikes": 93,
        "addToCart": 11,
        "purchases": 96,
        "normalRating": 3.66
    },
    {
        "id": 66,
        "productName": "Cookies - Englishbay Chochip",
        "price": 32,
        "views": 31,
        "likes": 69,
        "dislikes": 39,
        "addToCart": 91,
        "purchases": 4,
        "normalRating": 4.65
    },
    {
        "id": 67,
        "productName": "Turkey Tenderloin Frozen",
        "price": 34,
        "views": 12,
        "likes": 92,
        "dislikes": 89,
        "addToCart": 23,
        "purchases": 19,
        "normalRating": 2.69
    },
    {
        "id": 68,
        "productName": "Beer - Mill St Organic",
        "price": 53,
        "views": 13,
        "likes": 77,
        "dislikes": 22,
        "addToCart": 7,
        "purchases": 87,
        "normalRating": 4.55
    },
    {
        "id": 69,
        "productName": "Beans - Fava, Canned",
        "price": 47,
        "views": 77,
        "likes": 83,
        "dislikes": 73,
        "addToCart": 48,
        "purchases": 19,
        "normalRating": 1.55
    },
    {
        "id": 70,
        "productName": "Beef Ground Medium",
        "price": 83,
        "views": 51,
        "likes": 73,
        "dislikes": 79,
        "addToCart": 33,
        "purchases": 97,
        "normalRating": 1.19
    },
    {
        "id": 71,
        "productName": "Carbonated Water - Cherry",
        "price": 82,
        "views": 41,
        "likes": 79,
        "dislikes": 65,
        "addToCart": 11,
        "purchases": 13,
        "normalRating": 3.35
    },
    {
        "id": 72,
        "productName": "Tomato - Tricolor Cherry",
        "price": 11,
        "views": 23,
        "likes": 35,
        "dislikes": 76,
        "addToCart": 49,
        "purchases": 93,
        "normalRating": 3.68
    },
    {
        "id": 73,
        "productName": "Nestea - Iced Tea",
        "price": 67,
        "views": 74,
        "likes": 46,
        "dislikes": 89,
        "addToCart": 92,
        "purchases": 48,
        "normalRating": 1.22
    },
    {
        "id": 74,
        "productName": "Jolt Cola",
        "price": 52,
        "views": 36,
        "likes": 52,
        "dislikes": 23,
        "addToCart": 77,
        "purchases": 5,
        "normalRating": 3.36
    },
    {
        "id": 75,
        "productName": "Eggplant Italian",
        "price": 38,
        "views": 4,
        "likes": 93,
        "dislikes": 2,
        "addToCart": 99,
        "purchases": 76,
        "normalRating": 4.45
    },
    {
        "id": 76,
        "productName": "Wine - Dubouef Macon - Villages",
        "price": 59,
        "views": 44,
        "likes": 42,
        "dislikes": 100,
        "addToCart": 16,
        "purchases": 39,
        "normalRating": 3.94
    },
    {
        "id": 77,
        "productName": "Brocolinni - Gaylan, Chinese",
        "price": 34,
        "views": 52,
        "likes": 6,
        "dislikes": 97,
        "addToCart": 56,
        "purchases": 27,
        "normalRating": 3.67
    },
    {
        "id": 78,
        "productName": "Cheese - Perron Cheddar",
        "price": 68,
        "views": 19,
        "likes": 74,
        "dislikes": 39,
        "addToCart": 40,
        "purchases": 87,
        "normalRating": 1.23
    },
    {
        "id": 79,
        "productName": "Juice - Apple 284ml",
        "price": 70,
        "views": 48,
        "likes": 65,
        "dislikes": 79,
        "addToCart": 36,
        "purchases": 72,
        "normalRating": 4.7
    },
    {
        "id": 80,
        "productName": "Cheese - Perron Cheddar",
        "price": 90,
        "views": 23,
        "likes": 54,
        "dislikes": 38,
        "addToCart": 88,
        "purchases": 96,
        "normalRating": 1.64
    },
    {
        "id": 81,
        "productName": "Towels - Paper / Kraft",
        "price": 66,
        "views": 81,
        "likes": 50,
        "dislikes": 50,
        "addToCart": 14,
        "purchases": 97,
        "normalRating": 3.85
    },
    {
        "id": 82,
        "productName": "Melon - Watermelon Yellow",
        "price": 9,
        "views": 57,
        "likes": 88,
        "dislikes": 44,
        "addToCart": 34,
        "purchases": 3,
        "normalRating": 1.18
    },
    {
        "id": 83,
        "productName": "Blueberries - Frozen",
        "price": 31,
        "views": 9,
        "likes": 29,
        "dislikes": 27,
        "addToCart": 63,
        "purchases": 79,
        "normalRating": 2.79
    },
    {
        "id": 84,
        "productName": "Corn - On The Cob",
        "price": 12,
        "views": 17,
        "likes": 12,
        "dislikes": 2,
        "addToCart": 54,
        "purchases": 46,
        "normalRating": 3.12
    },
    {
        "id": 85,
        "productName": "Beans - Yellow",
        "price": 46,
        "views": 87,
        "likes": 10,
        "dislikes": 70,
        "addToCart": 47,
        "purchases": 60,
        "normalRating": 4.67
    },
    {
        "id": 86,
        "productName": "Wine - Barolo Fontanafredda",
        "price": 7,
        "views": 51,
        "likes": 49,
        "dislikes": 35,
        "addToCart": 72,
        "purchases": 25,
        "normalRating": 2.86
    },
    {
        "id": 87,
        "productName": "Celery",
        "price": 2,
        "views": 48,
        "likes": 26,
        "dislikes": 23,
        "addToCart": 1,
        "purchases": 86,
        "normalRating": 4.07
    },
    {
        "id": 88,
        "productName": "Wine - Ruffino Chianti",
        "price": 76,
        "views": 73,
        "likes": 82,
        "dislikes": 77,
        "addToCart": 24,
        "purchases": 53,
        "normalRating": 1.82
    },
    {
        "id": 89,
        "productName": "Soho Lychee Liqueur",
        "price": 54,
        "views": 92,
        "likes": 13,
        "dislikes": 54,
        "addToCart": 42,
        "purchases": 98,
        "normalRating": 1.6
    },
    {
        "id": 90,
        "productName": "Sauce - White, Mix",
        "price": 95,
        "views": 89,
        "likes": 90,
        "dislikes": 37,
        "addToCart": 40,
        "purchases": 33,
        "normalRating": 2.03
    },
    {
        "id": 91,
        "productName": "Wine - Acient Coast Caberne",
        "price": 39,
        "views": 13,
        "likes": 90,
        "dislikes": 30,
        "addToCart": 5,
        "purchases": 96,
        "normalRating": 2.98
    },
    {
        "id": 92,
        "productName": "Chips - Assorted",
        "price": 8,
        "views": 44,
        "likes": 21,
        "dislikes": 91,
        "addToCart": 39,
        "purchases": 18,
        "normalRating": 3.57
    },
    {
        "id": 93,
        "productName": "Beans - Long, Chinese",
        "price": 88,
        "views": 51,
        "likes": 77,
        "dislikes": 66,
        "addToCart": 57,
        "purchases": 12,
        "normalRating": 2.16
    },
    {
        "id": 94,
        "productName": "Wine - White, Antinore Orvieto",
        "price": 61,
        "views": 75,
        "likes": 60,
        "dislikes": 75,
        "addToCart": 82,
        "purchases": 67,
        "normalRating": 2.15
    },
    {
        "id": 95,
        "productName": "Lychee",
        "price": 9,
        "views": 47,
        "likes": 100,
        "dislikes": 3,
        "addToCart": 60,
        "purchases": 15,
        "normalRating": 1.46
    },
    {
        "id": 96,
        "productName": "Pork - Liver",
        "price": 97,
        "views": 56,
        "likes": 23,
        "dislikes": 92,
        "addToCart": 1,
        "purchases": 19,
        "normalRating": 1.17
    },
    {
        "id": 97,
        "productName": "Vinegar - Balsamic, White",
        "price": 30,
        "views": 88,
        "likes": 42,
        "dislikes": 55,
        "addToCart": 1,
        "purchases": 84,
        "normalRating": 4.12
    },
    {
        "id": 98,
        "productName": "Curry Paste - Madras",
        "price": 96,
        "views": 83,
        "likes": 11,
        "dislikes": 68,
        "addToCart": 73,
        "purchases": 16,
        "normalRating": 4.26
    },
    {
        "id": 99,
        "productName": "Swiss Chard",
        "price": 28,
        "views": 62,
        "likes": 73,
        "dislikes": 73,
        "addToCart": 61,
        "purchases": 48,
        "normalRating": 2.95
    },
    {
        "id": 100,
        "productName": "Cotton Wet Mop 16 Oz",
        "price": 31,
        "views": 86,
        "likes": 32,
        "dislikes": 43,
        "addToCart": 33,
        "purchases": 100,
        "normalRating": 1.71
    }
]
// eslint-disable-next-line react-refresh/only-export-components
export const PRODUCTS1 = [
    {
        "id": 1,
        "productName": "Broom - Corn",
        "price": 10,
        "views": 66,
        "likes": 75,
        "dislikes": 53,
        "addToCart": 9,
        "purchases": 64,
        "normalRating": 1.08
    },
    {
        "id": 2,
        "productName": "Peppercorns - Green",
        "price": 78,
        "views": 96,
        "likes": 78,
        "dislikes": 45,
        "addToCart": 27,
        "purchases": 82,
        "normalRating": 4.12
    },
    {
        "id": 3,
        "productName": "Tea - Orange Pekoe",
        "price": 89,
        "views": 28,
        "likes": 19,
        "dislikes": 29,
        "addToCart": 85,
        "purchases": 59,
        "normalRating": 4.44
    },
    {
        "id": 4,
        "productName": "Wine - Ruffino Chianti Classico",
        "price": 44,
        "views": 52,
        "likes": 93,
        "dislikes": 24,
        "addToCart": 48,
        "purchases": 21,
        "normalRating": 5.0
    },
    {
        "id": 5,
        "productName": "Longos - Penne With Pesto",
        "price": 66,
        "views": 16,
        "likes": 93,
        "dislikes": 85,
        "addToCart": 28,
        "purchases": 61,
        "normalRating": 3.64
    },
    {
        "id": 6,
        "productName": "Towel Dispenser",
        "price": 76,
        "views": 74,
        "likes": 8,
        "dislikes": 69,
        "addToCart": 65,
        "purchases": 32,
        "normalRating": 1.35
    },
    {
        "id": 7,
        "productName": "Sproutsmustard Cress",
        "price": 14,
        "views": 46,
        "likes": 3,
        "dislikes": 79,
        "addToCart": 74,
        "purchases": 73,
        "normalRating": 4.95
    },
    {
        "id": 8,
        "productName": "Beef Flat Iron Steak",
        "price": 100,
        "views": 43,
        "likes": 95,
        "dislikes": 48,
        "addToCart": 87,
        "purchases": 25,
        "normalRating": 4.43
    },
    {
        "id": 9,
        "productName": "Banana Turning",
        "price": 88,
        "views": 77,
        "likes": 48,
        "dislikes": 57,
        "addToCart": 30,
        "purchases": 33,
        "normalRating": 3.38
    },
    {
        "id": 10,
        "productName": "Icecream - Dstk Cml And Fdg",
        "price": 72,
        "views": 32,
        "likes": 74,
        "dislikes": 19,
        "addToCart": 79,
        "purchases": 10,
        "normalRating": 1.31
    },
    {
        "id": 11,
        "productName": "Scotch - Queen Anne",
        "price": 54,
        "views": 53,
        "likes": 64,
        "dislikes": 59,
        "addToCart": 99,
        "purchases": 80,
        "normalRating": 1.89
    },
    {
        "id": 12,
        "productName": "Cup - 3.5oz, Foam",
        "price": 54,
        "views": 79,
        "likes": 51,
        "dislikes": 58,
        "addToCart": 89,
        "purchases": 8,
        "normalRating": 4.7
    },
    {
        "id": 13,
        "productName": "French Pastry - Mini Chocolate",
        "price": 40,
        "views": 60,
        "likes": 9,
        "dislikes": 45,
        "addToCart": 27,
        "purchases": 37,
        "normalRating": 3.77
    },
    {
        "id": 14,
        "productName": "Yokaline",
        "price": 86,
        "views": 4,
        "likes": 88,
        "dislikes": 49,
        "addToCart": 93,
        "purchases": 84,
        "normalRating": 1.11
    },
    {
        "id": 15,
        "productName": "Soup - Campbells Beef Stew",
        "price": 68,
        "views": 46,
        "likes": 89,
        "dislikes": 39,
        "addToCart": 30,
        "purchases": 10,
        "normalRating": 3.73
    },
    {
        "id": 16,
        "productName": "Cherries - Frozen",
        "price": 72,
        "views": 90,
        "likes": 95,
        "dislikes": 87,
        "addToCart": 89,
        "purchases": 26,
        "normalRating": 1.79
    },
    {
        "id": 17,
        "productName": "Crush - Orange, 355ml",
        "price": 1,
        "views": 41,
        "likes": 62,
        "dislikes": 67,
        "addToCart": 22,
        "purchases": 92,
        "normalRating": 3.73
    },
    {
        "id": 18,
        "productName": "Apple - Custard",
        "price": 57,
        "views": 15,
        "likes": 54,
        "dislikes": 33,
        "addToCart": 53,
        "purchases": 42,
        "normalRating": 1.66
    },
    {
        "id": 19,
        "productName": "Wine - Winzer Krems Gruner",
        "price": 33,
        "views": 71,
        "likes": 96,
        "dislikes": 13,
        "addToCart": 38,
        "purchases": 20,
        "normalRating": 4.43
    },
    {
        "id": 20,
        "productName": "Hot Chocolate - Individual",
        "price": 41,
        "views": 4,
        "likes": 11,
        "dislikes": 10,
        "addToCart": 60,
        "purchases": 59,
        "normalRating": 1.52
    },
    {
        "id": 21,
        "productName": "Wine - Chateauneuf Du Pape",
        "price": 50,
        "views": 34,
        "likes": 41,
        "dislikes": 5,
        "addToCart": 78,
        "purchases": 24,
        "normalRating": 3.94
    },
    {
        "id": 22,
        "productName": "Scallops - 10/20",
        "price": 35,
        "views": 36,
        "likes": 83,
        "dislikes": 29,
        "addToCart": 46,
        "purchases": 34,
        "normalRating": 1.67
    },
    {
        "id": 23,
        "productName": "Longos - Lasagna Beef",
        "price": 61,
        "views": 98,
        "likes": 41,
        "dislikes": 25,
        "addToCart": 34,
        "purchases": 82,
        "normalRating": 2.79
    },
    {
        "id": 24,
        "productName": "Pancetta",
        "price": 47,
        "views": 63,
        "likes": 19,
        "dislikes": 29,
        "addToCart": 89,
        "purchases": 31,
        "normalRating": 2.13
    },
    {
        "id": 25,
        "productName": "Tart - Lemon",
        "price": 45,
        "views": 9,
        "likes": 94,
        "dislikes": 77,
        "addToCart": 69,
        "purchases": 8,
        "normalRating": 3.98
    },
    {
        "id": 26,
        "productName": "Plate Foam Laminated 9in Blk",
        "price": 18,
        "views": 91,
        "likes": 7,
        "dislikes": 97,
        "addToCart": 44,
        "purchases": 37,
        "normalRating": 1.79
    },
    {
        "id": 27,
        "productName": "Eggs - Extra Large",
        "price": 94,
        "views": 56,
        "likes": 91,
        "dislikes": 44,
        "addToCart": 60,
        "purchases": 20,
        "normalRating": 2.07
    },
    {
        "id": 28,
        "productName": "Lotus Leaves",
        "price": 94,
        "views": 94,
        "likes": 48,
        "dislikes": 53,
        "addToCart": 83,
        "purchases": 15,
        "normalRating": 4.58
    },
    {
        "id": 29,
        "productName": "Milk - 1%",
        "price": 2,
        "views": 7,
        "likes": 63,
        "dislikes": 22,
        "addToCart": 50,
        "purchases": 29,
        "normalRating": 3.37
    },
    {
        "id": 30,
        "productName": "Tuna - Canned, Flaked, Light",
        "price": 90,
        "views": 98,
        "likes": 8,
        "dislikes": 10,
        "addToCart": 78,
        "purchases": 37,
        "normalRating": 1.68
    },
    {
        "id": 31,
        "productName": "Bread Bowl Plain",
        "price": 20,
        "views": 52,
        "likes": 31,
        "dislikes": 34,
        "addToCart": 31,
        "purchases": 3,
        "normalRating": 1.7
    },
    {
        "id": 32,
        "productName": "Juice - Lagoon Mango",
        "price": 60,
        "views": 3,
        "likes": 64,
        "dislikes": 38,
        "addToCart": 36,
        "purchases": 80,
        "normalRating": 3.96
    },
    {
        "id": 33,
        "productName": "Pastrami",
        "price": 77,
        "views": 71,
        "likes": 84,
        "dislikes": 98,
        "addToCart": 5,
        "purchases": 23,
        "normalRating": 1.23
    },
    {
        "id": 34,
        "productName": "Cotton Wet Mop 16 Oz",
        "price": 98,
        "views": 78,
        "likes": 37,
        "dislikes": 63,
        "addToCart": 23,
        "purchases": 5,
        "normalRating": 2.57
    },
    {
        "id": 35,
        "productName": "Venison - Ground",
        "price": 12,
        "views": 55,
        "likes": 34,
        "dislikes": 18,
        "addToCart": 51,
        "purchases": 34,
        "normalRating": 4.87
    },
    {
        "id": 36,
        "productName": "Tomato - Peeled Italian Canned",
        "price": 29,
        "views": 24,
        "likes": 30,
        "dislikes": 36,
        "addToCart": 61,
        "purchases": 14,
        "normalRating": 2.59
    },
    {
        "id": 37,
        "productName": "Cup Translucent 9 Oz",
        "price": 74,
        "views": 28,
        "likes": 42,
        "dislikes": 11,
        "addToCart": 30,
        "purchases": 17,
        "normalRating": 2.86
    },
    {
        "id": 38,
        "productName": "Roe - Flying Fish",
        "price": 55,
        "views": 82,
        "likes": 11,
        "dislikes": 28,
        "addToCart": 59,
        "purchases": 58,
        "normalRating": 4.19
    },
    {
        "id": 39,
        "productName": "Soup - Campbells, Chix Gumbo",
        "price": 3,
        "views": 80,
        "likes": 75,
        "dislikes": 61,
        "addToCart": 40,
        "purchases": 96,
        "normalRating": 2.64
    },
    {
        "id": 40,
        "productName": "Tea - Earl Grey",
        "price": 88,
        "views": 19,
        "likes": 13,
        "dislikes": 29,
        "addToCart": 9,
        "purchases": 24,
        "normalRating": 3.94
    },
    {
        "id": 41,
        "productName": "Extract - Lemon",
        "price": 56,
        "views": 18,
        "likes": 99,
        "dislikes": 1,
        "addToCart": 20,
        "purchases": 90,
        "normalRating": 2.03
    },
    {
        "id": 42,
        "productName": "Pasta - Fusili Tri - Coloured",
        "price": 78,
        "views": 50,
        "likes": 40,
        "dislikes": 68,
        "addToCart": 70,
        "purchases": 28,
        "normalRating": 4.31
    },
    {
        "id": 43,
        "productName": "Ham - Smoked, Bone - In",
        "price": 7,
        "views": 39,
        "likes": 94,
        "dislikes": 95,
        "addToCart": 95,
        "purchases": 38,
        "normalRating": 1.24
    },
    {
        "id": 44,
        "productName": "Pomello",
        "price": 51,
        "views": 100,
        "likes": 10,
        "dislikes": 65,
        "addToCart": 96,
        "purchases": 15,
        "normalRating": 3.7
    },
    {
        "id": 45,
        "productName": "Ecolab Crystal Fusion",
        "price": 78,
        "views": 66,
        "likes": 30,
        "dislikes": 41,
        "addToCart": 15,
        "purchases": 58,
        "normalRating": 1.94
    },
    {
        "id": 46,
        "productName": "Chocolate - Feathers",
        "price": 24,
        "views": 33,
        "likes": 68,
        "dislikes": 54,
        "addToCart": 22,
        "purchases": 77,
        "normalRating": 1.38
    },
    {
        "id": 47,
        "productName": "Yogurt - Cherry, 175 Gr",
        "price": 18,
        "views": 62,
        "likes": 86,
        "dislikes": 28,
        "addToCart": 74,
        "purchases": 81,
        "normalRating": 3.91
    },
    {
        "id": 48,
        "productName": "Turkey - Oven Roast Breast",
        "price": 55,
        "views": 39,
        "likes": 71,
        "dislikes": 1,
        "addToCart": 8,
        "purchases": 40,
        "normalRating": 2.2
    },
    {
        "id": 49,
        "productName": "Wine - Delicato Merlot",
        "price": 8,
        "views": 86,
        "likes": 66,
        "dislikes": 36,
        "addToCart": 70,
        "purchases": 62,
        "normalRating": 1.3
    },
    {
        "id": 50,
        "productName": "Pepper - Sorrano",
        "price": 33,
        "views": 25,
        "likes": 1,
        "dislikes": 84,
        "addToCart": 81,
        "purchases": 6,
        "normalRating": 2.57
    },
    {
        "id": 51,
        "productName": "Cheese - Grie Des Champ",
        "price": 62,
        "views": 7,
        "likes": 77,
        "dislikes": 12,
        "addToCart": 90,
        "purchases": 86,
        "normalRating": 3.47
    },
    {
        "id": 52,
        "productName": "Ice Cream - Vanilla",
        "price": 40,
        "views": 47,
        "likes": 80,
        "dislikes": 47,
        "addToCart": 88,
        "purchases": 88,
        "normalRating": 3.58
    },
    {
        "id": 53,
        "productName": "Juice Peach Nectar",
        "price": 4,
        "views": 83,
        "likes": 32,
        "dislikes": 69,
        "addToCart": 29,
        "purchases": 12,
        "normalRating": 1.06
    },
    {
        "id": 54,
        "productName": "Cod - Black Whole Fillet",
        "price": 65,
        "views": 37,
        "likes": 33,
        "dislikes": 95,
        "addToCart": 53,
        "purchases": 19,
        "normalRating": 1.6
    },
    {
        "id": 55,
        "productName": "Soup - Campbells - Chicken Noodle",
        "price": 72,
        "views": 64,
        "likes": 54,
        "dislikes": 5,
        "addToCart": 34,
        "purchases": 30,
        "normalRating": 2.21
    },
    {
        "id": 56,
        "productName": "Kellogs Special K Cereal",
        "price": 24,
        "views": 79,
        "likes": 77,
        "dislikes": 37,
        "addToCart": 51,
        "purchases": 63,
        "normalRating": 1.66
    },
    {
        "id": 57,
        "productName": "Crab - Soft Shell",
        "price": 2,
        "views": 97,
        "likes": 59,
        "dislikes": 60,
        "addToCart": 56,
        "purchases": 21,
        "normalRating": 4.62
    },
    {
        "id": 58,
        "productName": "Coffee - Almond Amaretto",
        "price": 92,
        "views": 73,
        "likes": 96,
        "dislikes": 97,
        "addToCart": 56,
        "purchases": 45,
        "normalRating": 3.78
    },
    {
        "id": 59,
        "productName": "Ice Cream - Fudge Bars",
        "price": 99,
        "views": 24,
        "likes": 68,
        "dislikes": 11,
        "addToCart": 76,
        "purchases": 91,
        "normalRating": 3.98
    },
    {
        "id": 60,
        "productName": "Island Oasis - Ice Cream Mix",
        "price": 14,
        "views": 34,
        "likes": 23,
        "dislikes": 28,
        "addToCart": 76,
        "purchases": 50,
        "normalRating": 4.6
    },
    {
        "id": 61,
        "productName": "Bag - Regular Kraft 20 Lb",
        "price": 98,
        "views": 20,
        "likes": 90,
        "dislikes": 31,
        "addToCart": 100,
        "purchases": 25,
        "normalRating": 3.06
    },
    {
        "id": 62,
        "productName": "Tumeric",
        "price": 30,
        "views": 65,
        "likes": 76,
        "dislikes": 82,
        "addToCart": 51,
        "purchases": 51,
        "normalRating": 3.82
    },
    {
        "id": 63,
        "productName": "Wine - Chardonnay South",
        "price": 14,
        "views": 21,
        "likes": 93,
        "dislikes": 75,
        "addToCart": 70,
        "purchases": 14,
        "normalRating": 3.77
    },
    {
        "id": 64,
        "productName": "Juice - Propel Sport",
        "price": 46,
        "views": 59,
        "likes": 68,
        "dislikes": 57,
        "addToCart": 26,
        "purchases": 46,
        "normalRating": 1.38
    },
    {
        "id": 65,
        "productName": "Appetizer - Mushroom Tart",
        "price": 48,
        "views": 98,
        "likes": 30,
        "dislikes": 93,
        "addToCart": 11,
        "purchases": 96,
        "normalRating": 3.66
    },
    {
        "id": 66,
        "productName": "Cookies - Englishbay Chochip",
        "price": 32,
        "views": 31,
        "likes": 69,
        "dislikes": 39,
        "addToCart": 91,
        "purchases": 4,
        "normalRating": 4.65
    },
    {
        "id": 67,
        "productName": "Turkey Tenderloin Frozen",
        "price": 34,
        "views": 12,
        "likes": 92,
        "dislikes": 89,
        "addToCart": 23,
        "purchases": 19,
        "normalRating": 2.69
    },
    {
        "id": 68,
        "productName": "Beer - Mill St Organic",
        "price": 53,
        "views": 13,
        "likes": 77,
        "dislikes": 22,
        "addToCart": 7,
        "purchases": 87,
        "normalRating": 4.55
    },
    {
        "id": 69,
        "productName": "Beans - Fava, Canned",
        "price": 47,
        "views": 77,
        "likes": 83,
        "dislikes": 73,
        "addToCart": 48,
        "purchases": 19,
        "normalRating": 1.55
    },
    {
        "id": 70,
        "productName": "Beef Ground Medium",
        "price": 83,
        "views": 51,
        "likes": 73,
        "dislikes": 79,
        "addToCart": 33,
        "purchases": 97,
        "normalRating": 1.19
    },
    {
        "id": 71,
        "productName": "Carbonated Water - Cherry",
        "price": 82,
        "views": 41,
        "likes": 79,
        "dislikes": 65,
        "addToCart": 11,
        "purchases": 13,
        "normalRating": 3.35
    },
    {
        "id": 72,
        "productName": "Tomato - Tricolor Cherry",
        "price": 11,
        "views": 23,
        "likes": 35,
        "dislikes": 76,
        "addToCart": 49,
        "purchases": 93,
        "normalRating": 3.68
    },
    {
        "id": 73,
        "productName": "Nestea - Iced Tea",
        "price": 67,
        "views": 74,
        "likes": 46,
        "dislikes": 89,
        "addToCart": 92,
        "purchases": 48,
        "normalRating": 1.22
    },
    {
        "id": 74,
        "productName": "Jolt Cola",
        "price": 52,
        "views": 36,
        "likes": 52,
        "dislikes": 23,
        "addToCart": 77,
        "purchases": 5,
        "normalRating": 3.36
    },
    {
        "id": 75,
        "productName": "Eggplant Italian",
        "price": 38,
        "views": 4,
        "likes": 93,
        "dislikes": 2,
        "addToCart": 99,
        "purchases": 76,
        "normalRating": 4.45
    },
    {
        "id": 76,
        "productName": "Wine - Dubouef Macon - Villages",
        "price": 59,
        "views": 44,
        "likes": 42,
        "dislikes": 100,
        "addToCart": 16,
        "purchases": 39,
        "normalRating": 3.94
    },
    {
        "id": 77,
        "productName": "Brocolinni - Gaylan, Chinese",
        "price": 34,
        "views": 52,
        "likes": 6,
        "dislikes": 97,
        "addToCart": 56,
        "purchases": 27,
        "normalRating": 3.67
    },
    {
        "id": 78,
        "productName": "Cheese - Perron Cheddar",
        "price": 68,
        "views": 19,
        "likes": 74,
        "dislikes": 39,
        "addToCart": 40,
        "purchases": 87,
        "normalRating": 1.23
    },
    {
        "id": 79,
        "productName": "Juice - Apple 284ml",
        "price": 70,
        "views": 48,
        "likes": 65,
        "dislikes": 79,
        "addToCart": 36,
        "purchases": 72,
        "normalRating": 4.7
    },
    {
        "id": 80,
        "productName": "Cheese - Perron Cheddar",
        "price": 90,
        "views": 23,
        "likes": 54,
        "dislikes": 38,
        "addToCart": 88,
        "purchases": 96,
        "normalRating": 1.64
    },
    {
        "id": 81,
        "productName": "Towels - Paper / Kraft",
        "price": 66,
        "views": 81,
        "likes": 50,
        "dislikes": 50,
        "addToCart": 14,
        "purchases": 97,
        "normalRating": 3.85
    },
    {
        "id": 82,
        "productName": "Melon - Watermelon Yellow",
        "price": 9,
        "views": 57,
        "likes": 88,
        "dislikes": 44,
        "addToCart": 34,
        "purchases": 3,
        "normalRating": 1.18
    },
    {
        "id": 83,
        "productName": "Blueberries - Frozen",
        "price": 31,
        "views": 9,
        "likes": 29,
        "dislikes": 27,
        "addToCart": 63,
        "purchases": 79,
        "normalRating": 2.79
    },
    {
        "id": 84,
        "productName": "Corn - On The Cob",
        "price": 12,
        "views": 17,
        "likes": 12,
        "dislikes": 2,
        "addToCart": 54,
        "purchases": 46,
        "normalRating": 3.12
    },
    {
        "id": 85,
        "productName": "Beans - Yellow",
        "price": 46,
        "views": 87,
        "likes": 10,
        "dislikes": 70,
        "addToCart": 47,
        "purchases": 60,
        "normalRating": 4.67
    },
    {
        "id": 86,
        "productName": "Wine - Barolo Fontanafredda",
        "price": 7,
        "views": 51,
        "likes": 49,
        "dislikes": 35,
        "addToCart": 72,
        "purchases": 25,
        "normalRating": 2.86
    },
    {
        "id": 87,
        "productName": "Celery",
        "price": 2,
        "views": 48,
        "likes": 26,
        "dislikes": 23,
        "addToCart": 1,
        "purchases": 86,
        "normalRating": 4.07
    },
    {
        "id": 88,
        "productName": "Wine - Ruffino Chianti",
        "price": 76,
        "views": 73,
        "likes": 82,
        "dislikes": 77,
        "addToCart": 24,
        "purchases": 53,
        "normalRating": 1.82
    },
    {
        "id": 89,
        "productName": "Soho Lychee Liqueur",
        "price": 54,
        "views": 92,
        "likes": 13,
        "dislikes": 54,
        "addToCart": 42,
        "purchases": 98,
        "normalRating": 1.6
    },
    {
        "id": 90,
        "productName": "Sauce - White, Mix",
        "price": 95,
        "views": 89,
        "likes": 90,
        "dislikes": 37,
        "addToCart": 40,
        "purchases": 33,
        "normalRating": 2.03
    },
    {
        "id": 91,
        "productName": "Wine - Acient Coast Caberne",
        "price": 39,
        "views": 13,
        "likes": 90,
        "dislikes": 30,
        "addToCart": 5,
        "purchases": 96,
        "normalRating": 2.98
    },
    {
        "id": 92,
        "productName": "Chips - Assorted",
        "price": 8,
        "views": 44,
        "likes": 21,
        "dislikes": 91,
        "addToCart": 39,
        "purchases": 18,
        "normalRating": 3.57
    },
    {
        "id": 93,
        "productName": "Beans - Long, Chinese",
        "price": 88,
        "views": 51,
        "likes": 77,
        "dislikes": 66,
        "addToCart": 57,
        "purchases": 12,
        "normalRating": 2.16
    },
    {
        "id": 94,
        "productName": "Wine - White, Antinore Orvieto",
        "price": 61,
        "views": 75,
        "likes": 60,
        "dislikes": 75,
        "addToCart": 82,
        "purchases": 67,
        "normalRating": 2.15
    },
    {
        "id": 95,
        "productName": "Lychee",
        "price": 9,
        "views": 47,
        "likes": 100,
        "dislikes": 3,
        "addToCart": 60,
        "purchases": 15,
        "normalRating": 1.46
    },
    {
        "id": 96,
        "productName": "Pork - Liver",
        "price": 97,
        "views": 56,
        "likes": 23,
        "dislikes": 92,
        "addToCart": 1,
        "purchases": 19,
        "normalRating": 1.17
    },
    {
        "id": 97,
        "productName": "Vinegar - Balsamic, White",
        "price": 30,
        "views": 88,
        "likes": 42,
        "dislikes": 55,
        "addToCart": 1,
        "purchases": 84,
        "normalRating": 4.12
    },
    {
        "id": 98,
        "productName": "Curry Paste - Madras",
        "price": 96,
        "views": 83,
        "likes": 11,
        "dislikes": 68,
        "addToCart": 73,
        "purchases": 16,
        "normalRating": 4.26
    },
    {
        "id": 99,
        "productName": "Swiss Chard",
        "price": 28,
        "views": 62,
        "likes": 73,
        "dislikes": 73,
        "addToCart": 61,
        "purchases": 48,
        "normalRating": 2.95
    },
    {
        "id": 100,
        "productName": "Cotton Wet Mop 16 Oz",
        "price": 31,
        "views": 86,
        "likes": 32,
        "dislikes": 43,
        "addToCart": 33,
        "purchases": 100,
        "normalRating": 1.71
    }

];